[package]
name = "jellyfish"
version = "0.1.0"
authors = ["Hiroki Noda <kubo39@gmail.com>"]

[[bin]]
name = "httpd"
path = "src/bin/httpd.rs"

[dependencies]
linux_aio = { git = "https://github.com/sile/linux_aio", tag = "0.0.1" }
